### ISSUE TITLE
problem when recording data via RealTerm 

### ISSUE THREAD

**Issue by chaabanihoussem** [gregtomasch/nRF52_24-bit-_I2S_Microphone_Audio_Recording_Utility#2]
i have been recording data with RealTerm and trying to listen to it via Audacity but i have got always a very bad sound. i tried with start offsets of 1, 2 or 3 bytes but it's still the same problem.

**Comment by gregtomasch** [comment]
What baud rate are you using?

**Comment by chaabanihoussem** [comment]
i used 921600 but the data stop passing over the terminal, then i tested with a high performance  pc and it works, so the problem was the baud rate of my pc(limited at 115200).
thank you
