### ISSUE TITLE
SOFTDEVICE?

### ISSUE THREAD

**Issue by jkuzma** [gregtomasch/nRF52_24-bit-_I2S_Microphone_Audio_Recording_Utility#3]
Hello,

Very slick solution.

More of a question than an issue here...
Has the code been tested with a SOFTDEVICE?
ie. active BLE connection.

Thanks
-JK

**Comment by gregtomasch** [comment]
Hi JK,

Sorry for the slow reply; I had some rather pressing life issues...

Yes, this has been successfully integrated into BLE peripheral Apps...

Best,
Greg
